version: '3'
services:
  db:
    image: postgres:10.12
    ports:
      - "5436:5432"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./init-script:/docker-entrypoint-initdb.d
  service1:
    image: "service1"
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
volumes:
  database-data:
